#some nice message/envelope/graph data
# 1. save as export-edges.csv,
# 2. add this line to top: Source,label,Target,weight,EdgeType, Start, End
# 3. Import into gephi
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix msg: <http://purl.org/webofneeds/message#>
prefix won: <http://purl.org/webofneeds/model#>
prefix dcterm: <http://purl.org/dc/terms/>
PREFIX xsd:    <http://www.w3.org/2001/XMLSchema#>

select  distinct
    ?c ?s ?label ?o ?weight ?state ?edgetype ?start ?end
where
{
    {
        
        ?c a won:Connection;
           won:belongsToNeed ?n1;
           won:hasRemoteNeed ?n2;
           won:hasConnectionState ?state;
           dcterm:modified ?mod . 
        BIND(?n1 as ?s)
        BIND(?n2 as ?o)
        BIND(1 as ?weight)
        BIND("conn" as ?edgetype)
        BIND(?mod as ?start)
        BIND(now() as ?end)
        FILTER (?mod > "2018-06-01T00:00:00Z"^^xsd:dateTime )
    } 
 } order by ?start 
 